Parameters: 
  MyBucketName:
    Description: "input s3 bucket name."
    Type: String
  MyDDBName:
    Description: "input dynamodb table name." 
    Type: String
Resources: 
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  MyDDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref MyDDBName
      AttributeDefinitions:
        - AttributeName: "SongTitle"
          AttributeType: "S"
        - AttributeName: "Singer"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "SongTitle"
          KeyType: "HASH"
        - AttributeName: "Singer"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
Outputs:
  MyS3BucketId:
    Value: !Ref MyS3Bucket
    Export:
      Name: MyS3BucketId
  MyDDBTableId:
    Value: !Ref MyDDBTable
    Export:
      Name: MyDDBTableId
